<section class="hero-section relative min-h-screen bg-white flex items-center justify-center overflow-hidden">
  <!-- Floating Clouds Background Animation -->
  <div id="floating-clouds" class="absolute inset-0 z-2 pointer-events-none">
    <!-- Clouds will be dynamically generated by JavaScript -->
  </div>
  
  <!-- Dot Pattern Background -->
  <div class="dot-pattern absolute inset-0 bg-gradient-to-br from-gray-50 to-white opacity-50 z-1"></div>
  
  <!-- Hero Content -->
  <div class="hero-content relative z-10 text-center max-w-4xl px-6">
    <!-- Company Name with Dots -->
    <div class="company-name relative inline-block text-gray-500 text-2xl font-light tracking-wider mb-8 opacity-70">
      <span class="dot dot-left absolute top-1/2 left-[-20px] w-2 h-2 bg-gray-300 rounded-full transform -translate-y-1/2"></span>
      Aksara Sinergi Teknologi
      <span class="dot dot-right absolute top-1/2 right-[-20px] w-2 h-2 bg-gray-300 rounded-full transform -translate-y-1/2"></span>
    </div>
    
    <!-- Main Heading -->
    <h1 class="main-heading text-black text-5xl md:text-6xl lg:text-7xl font-black mb-8 leading-tight">Grow With Us</h1>
    
    <!-- Hero Image -->
    <div class="hero-image mt-8 max-w-full animate-fade-in-up">
      <img src="{{ Vite::asset('resources/images/lentera-hero.png') }}" alt="Technology Solutions" class="max-w-full h-auto rounded-lg" />
    </div>
  </div>
</section>

<style>
/* Cloud Shape Styling - This needs custom CSS */
.cloud {
  background: linear-gradient(135deg, #60a5fa, #3b82f6);
  opacity: 0.1;
  border-radius: 100px;
  position: absolute;
}

.cloud::before,
.cloud::after {
  content: '';
  position: absolute;
  background: linear-gradient(135deg, #60a5fa, #3b82f6);
  border-radius: 100px;
}

/* Fade In Animation for Hero Image */
@keyframes fade-in-up {
  from {
    opacity: 0;
    transform: translateY(30px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.animate-fade-in-up { animation: fade-in-up 1s ease-out; }
</style>

<script>
document.addEventListener('DOMContentLoaded', function() {
  const cloudsContainer = document.getElementById('floating-clouds');
  const windowWidth = window.innerWidth;
  
  // Determine number of clouds based on screen size
  let cloudCount;
  if (windowWidth >= 1024) {
    cloudCount = 30; // Desktop
  } else if (windowWidth >= 768) {
    cloudCount = 22; // Tablet
  } else {
    cloudCount = 16; // Mobile
  }
  
  // Generate clouds
  for (let i = 1; i <= cloudCount; i++) {
    createCloud(i);
  }
  
  function createCloud(index) {
    const cloud = document.createElement('div');
    cloud.className = 'cloud';
    
    // Random positioning
    const top = Math.random() * 80 + 10; // 10% to 90% from top
    const left = Math.random() * 80 + 10; // 10% to 90% from left
    
    cloud.style.top = `${top}%`;
    cloud.style.left = `${left}%`;
    
    // Responsive sizing
    let width, height;
    if (windowWidth >= 1024) {
      // Desktop sizes
      width = Math.random() * 100 + 180; // 180px to 280px
      height = width * 0.4; // Maintain aspect ratio
    } else if (windowWidth >= 768) {
      // Tablet sizes
      width = Math.random() * 80 + 120; // 120px to 200px
      height = width * 0.4;
    } else {
      // Mobile sizes
      width = Math.random() * 60 + 90; // 90px to 150px
      height = width * 0.4;
    }
    
    cloud.style.width = `${width}px`;
    cloud.style.height = `${height}px`;
    
    // Create pseudo-elements for cloud shape
    const before = document.createElement('div');
    before.style.position = 'absolute';
    before.style.background = 'linear-gradient(135deg, #60a5fa, #3b82f6)';
    before.style.borderRadius = '100px';
    before.style.width = `${width * 0.5}px`;
    before.style.height = `${width * 0.5}px`;
    before.style.top = `-${width * 0.25}px`;
    before.style.left = `${width * 0.1}px`;
    
    const after = document.createElement('div');
    after.style.position = 'absolute';
    after.style.background = 'linear-gradient(135deg, #60a5fa, #3b82f6)';
    after.style.borderRadius = '100px';
    after.style.width = `${width * 0.6}px`;
    after.style.height = `${width * 0.3}px`;
    after.style.top = `-${width * 0.15}px`;
    after.style.right = `${width * 0.1}px`;
    
    cloud.appendChild(before);
    cloud.appendChild(after);
    
    // Add floating animation
    const animationDuration = Math.random() * 10 + 12; // 12s to 22s
    const animationDelay = Math.random() * 5; // 0s to 5s
    
    // Create unique keyframes for each cloud
    const keyframes = generateKeyframes(index);
    const style = document.createElement('style');
    style.textContent = keyframes;
    document.head.appendChild(style);
    
    cloud.style.animation = `float-${index} ${animationDuration}s infinite ease-in-out ${animationDelay}s`;
    
    cloudsContainer.appendChild(cloud);
  }
  
  function generateKeyframes(index) {
    const movement = Math.random() * 40 + 20; // 20px to 60px movement
    
    return `
      @keyframes float-${index} {
        0%, 100% {
          transform: translate(0, 0);
        }
        25% {
          transform: translate(${movement}px, ${-movement * 1.2}px);
        }
        50% {
          transform: translate(${-movement * 0.8}px, ${-movement * 1.5}px);
        }
        75% {
          transform: translate(${-movement * 1.2}px, ${-movement * 0.6}px);
        }
      }
    `;
  }
  
  // Regenerate clouds on window resize
  let resizeTimeout;
  window.addEventListener('resize', function() {
    clearTimeout(resizeTimeout);
    resizeTimeout = setTimeout(function() {
      cloudsContainer.innerHTML = '';
      const newWindowWidth = window.innerWidth;
      
      let newCloudCount;
      if (newWindowWidth >= 1024) {
        newCloudCount = 25;
      } else if (newWindowWidth >= 768) {
        newCloudCount = 15;
      } else {
        newCloudCount = 8;
      }
      
      for (let i = 1; i <= newCloudCount; i++) {
        createCloud(i);
      }
    }, 250);
  });
});
</script>